// <auto-generated />
using System;
using ITSM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITSM.Migrations
{
    [DbContext(typeof(ITSMContext))]
    [Migration("20250401174344_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITSM.Entity.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ContractingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLA")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractingDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Providing reliable and fast web hosting services.",
                            Name = "Web Hosting",
                            SLA = 99,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            ContractingDate = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Scalable cloud storage solutions for businesses of all sizes.",
                            Name = "Cloud Storage",
                            SLA = 99,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            ContractingDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Email marketing campaigns, automation, and reporting.",
                            Name = "Email Marketing",
                            SLA = 98,
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            ContractingDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Secure backup and disaster recovery solutions.",
                            Name = "Data Backup",
                            SLA = 97,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            ContractingDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Search engine optimization to increase website visibility.",
                            Name = "SEO Optimization",
                            SLA = 95,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ITSM.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jdoe@example.com",
                            Group = "Admin",
                            Login = "jdoe",
                            Name = "John",
                            Occupation = "Software Engineer",
                            Password = "Password123",
                            Status = "Active",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asmith@example.com",
                            Group = "User",
                            Login = "asmith",
                            Name = "Alice",
                            Occupation = "Product Manager",
                            Password = "SecurePass456",
                            Status = "Active",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bjohnson@example.com",
                            Group = "Moderator",
                            Login = "bjohnson",
                            Name = "Bob",
                            Occupation = "QA Engineer",
                            Password = "TestPass789",
                            Status = "Inactive",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "klane@example.com",
                            Group = "User",
                            Login = "klane",
                            Name = "Kate",
                            Occupation = "UX Designer",
                            Password = "KatePass999",
                            Status = "Active",
                            Surname = "Lane"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mwhite@example.com",
                            Group = "Admin",
                            Login = "mwhite",
                            Name = "Michael",
                            Occupation = "CTO",
                            Password = "MikePass111",
                            Status = "Suspended",
                            Surname = "White"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
